# 状态检查工作流的名称
name: No Zero Change Push

# 事件触发条件，当有推送或者合并请求时触发
on: [push, pull_request]

# 工作流中的任务
jobs:
  # 任务的名称
  no-zero-change-push:
    # 任务的运行环境，使用最新的 Ubuntu 系统
    runs-on: ubuntu-latest
    # 任务的步骤
    steps:
      # 第一步，使用 actions/checkout 动作，获取当前分支的代码
      - name: Checkout
        uses: actions/checkout@v2
      # 第二步，使用 actions/github-script 动作，执行 JavaScript 代码
      - name: Run script
        uses: actions/github-script@v4
        # 传递给动作的参数
        with:
          # 要执行的 JavaScript 代码
          script: |
            // 使用 GitHub API 比较主分支和当前分支之间的差异
            const response = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: 'main', // 主分支的名称，根据您的实际情况修改
              head: context.sha // 当前分支的最新提交的哈希值
            });
            // 获取比较结果中的提交数
            const totalCommits = response.data.total_commits;
            // 如果提交数为 0，说明没有任何变化，让状态检查失败
            if (totalCommits === 0) {
              core.setFailed('No changes detected. Pushing zero change commits is not allowed.'); // 您可以修改错误信息
            }
